# Generated by Django 4.2.3 on 2023-08-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisment', '0004_advertisement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(upload_to='advertisements/, null=True, blank=True', verbose_name='Изображение'),
        ),
    ]
